name: Deploy Terraform to AWS ECS

on:
  push:
    branches:
      - grafana-branch
    paths:
      - 'terraform/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init -backend-config="bucket=redshift-data-migration-bucket" \
                             -backend-config="key=grafana/terraform.tfstate" \
                             -backend-config="region=us-east-1" \
                             terraform/

      - name: Terraform Validate
        run: terraform validate terraform/

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false terraform/

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
